%{ if gridgain_config_defined ~}
#cloud-config
# vim: syntax=yaml

write_files:
%{ if gridgain_license_defined ~}
  - path: /opt/gridgain/config/license.xml
    encoding: gzip
    content: !!binary |
      ${gridgain_license}
%{ endif ~}
  - path: /opt/gridgain/config/server.xml
    encoding: gzip
    content: !!binary |
      ${gridgain_config}
%{ if ssl_enable ~}
  - path: /opt/gridgain/ssl/server.crt
    encoding: gzip
    content: !!binary |
      ${gridgain_ssl_cert}
  - path: /opt/gridgain/ssl/server.key
    encoding: gzip
    content: !!binary |
      ${gridgain_ssl_key}
  - path: /opt/gridgain/config/jetty.xml
    encoding: gzip
    content: !!binary |
      ${gridgain_jetty_config}
%{ endif ~}
  - path: /opt/gridgain/config/service.properties.override
    content: |
      EXTRA_OPTS=\
%{ if ssl_enable ~}
      -Djavax.net.ssl.keyStore=/opt/gridgain/ssl/server.jks \
      -Djavax.net.ssl.keyStorePassword=${keystore_password} \
%{~ endif ~}
%{ if can(public_ips[node_id]) ~}
      -Djava.rmi.server.hostname=${public_ips[node_id]}
%{~ endif ~}
%{ if gridgain_license_defined ~}
      CP=-cp /opt/gridgain/binaries/latest/libs/*:/opt/gridgain/binaries/latest/libs/gridgain-ultimate/*:/opt/gridgain/binaries/latest/libs/ignite-control-utility/*:/opt/gridgain/binaries/latest/libs/ignite-indexing/*:/opt/gridgain/binaries/latest/libs/ignite-opencensus/*:/opt/gridgain/binaries/latest/libs/ignite-spring/*:/opt/gridgain/binaries/latest/libs/licenses/*:/opt/gridgain/binaries/latest/libs/ignite-rest-http/*:/opt/gridgain/binaries/latest/libs/ignite-log4j2/*:/opt/gridgain/binaries/latest/libs/control-center-agent/*:/opt/gridgain/binaries/latest/libs/ignite-schedule/*:/opt/gridgain/binaries/latest/libs/ignite-aws/*
%{~ endif ~}

runcmd:
%{ if ssl_enable ~}
  - openssl pkcs12 -export -in /opt/gridgain/ssl/server.crt -inkey /opt/gridgain/ssl/server.key -name root -out /opt/gridgain/ssl/server.p12 -password pass:${keystore_password}
  - ln -s /opt/gridgain/ssl/server.p12 /opt/gridgain/ssl/server.jks
%{ endif ~}
  - chown -h gg_rw_user:gg_rw_group /opt/gridgain/config/* /opt/gridgain/ssl/*
  - chmod 0640 /opt/gridgain/config/* /opt/gridgain/ssl/*
  - rm -f /opt/gridgain/ssl/server.crt /opt/gridgain/ssl/server.key
  - systemctl restart gridgain
  - systemctl enable gridgain
%{ endif ~}
